# Generated by Django 3.2.1 on 2021-05-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fd_name", models.CharField(max_length=10)),
                ("fd_date", models.DateField()),
                ("fd_open", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fd_high", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fd_low", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fd_close", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fd_adj_close", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fd_volume", models.IntegerField()),
            ],
        ),
    ]
