# Generated by Django 3.2.1 on 2021-05-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DataScrapper", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="findatamodel",
            name="fd_adj_close",
        ),
    ]
